# Generated by Django 2.0.4 on 2018-04-20 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0003_auto_20180419_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='File')),
                ('name', models.CharField(max_length=50, verbose_name='文件名')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('emotionty', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default=0)),
                ('strength', models.IntegerField(default=0)),
            ],
        ),
    ]
