# Generated by Django 2.0.4 on 2018-04-20 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0004_importfile_word'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImportFile',
        ),
    ]
