# Generated by Django 2.0.4 on 2018-04-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0006_auto_20180420_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='strength0',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='diary',
            name='strength1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='diary',
            name='strength2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='diary',
            name='strength3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='diary',
            name='strength4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='diary',
            name='strength5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='diary',
            name='strength6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='diary',
            name='strength7',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='diary',
            name='emotion',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default=0),
        ),
    ]
