# Generated by Django 2.0.4 on 2018-04-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0007_auto_20180420_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pair_status',
            field=models.BooleanField(default=False),
        ),
    ]
