# Generated by Django 2.0.4 on 2018-04-29 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0013_auto_20180423_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(max_length=10000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matching.User')),
            ],
        ),
        migrations.AddField(
            model_name='pairing',
            name='pair_name',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
