# Generated by Django 2.0.4 on 2018-04-29 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0014_auto_20180429_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pairing',
            name='pair_name',
        ),
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='matching.Pairing'),
        ),
    ]
