# Generated by Django 2.0.4 on 2018-04-30 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0017_auto_20180429_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatarUrl',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickName',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='openId',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='user',
            name='province',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
