# Generated by Django 2.0.4 on 2018-04-30 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0018_auto_20180430_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
